[2023-11-04 14:20:15,243] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: people-schema.init scheduled__2023-07-01T00:00:00+00:00 [failed]>
[2023-11-04 14:20:15,261] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: people-schema.init scheduled__2023-07-01T00:00:00+00:00 [failed]>
[2023-11-04 14:20:15,262] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-11-04 14:20:15,264] {taskinstance.py:1244} INFO - Starting attempt 3 of 1
[2023-11-04 14:20:15,265] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2023-11-04 14:20:15,275] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): init> on 2023-07-01 00:00:00+00:00
[2023-11-04 14:20:15,281] {standard_task_runner.py:52} INFO - Started process 352 to run task
[2023-11-04 14:20:15,287] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'people-schema', 'init', 'scheduled__2023-07-01T00:00:00+00:00', '--job-id', '11', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/people-schema.py', '--cfg-path', '/tmp/tmpeydp9unr', '--error-file', '/tmp/tmplqp8i80u']
[2023-11-04 14:20:15,288] {standard_task_runner.py:77} INFO - Job 11: Subtask init
[2023-11-04 14:20:15,366] {logging_mixin.py:109} INFO - Running <TaskInstance: people-schema.init scheduled__2023-07-01T00:00:00+00:00 [running]> on host f5a9780aa73a
[2023-11-04 14:20:15,423] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=people-schema
AIRFLOW_CTX_TASK_ID=init
AIRFLOW_CTX_EXECUTION_DATE=2023-07-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-01T00:00:00+00:00
[2023-11-04 14:20:15,437] {base.py:70} INFO - Using connection to: id: test_conn. Host: host.docker.internal, Port: 15432, Schema: , Login: ***, Password: ***, extra: {}
[2023-11-04 14:20:15,449] {base.py:70} INFO - Using connection to: id: test_conn. Host: host.docker.internal, Port: 15432, Schema: , Login: ***, Password: ***, extra: {}
[2023-11-04 14:20:15,598] {python.py:175} INFO - Done. Returned value was: None
[2023-11-04 14:20:15,618] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=people-schema, task_id=init, execution_date=20230701T000000, start_date=20231104T142015, end_date=20231104T142015
[2023-11-04 14:20:15,662] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-11-04 14:20:15,700] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
